### PR TITLE
dedicated var for query_status, legend and show-messages visualization bug, sanitizing form before submit 

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Comment by burnout87** [comment]
aligning with the changes from https://github.com/oda-hub/dispatcher-app/pull/670

**Comment by burnout87** [comment]
also to address https://github.com/oda-hub/mmoda-frontend-module/issues/250

**Comment by volodymyrss** [comment]
So should we merge it?

**Comment by burnout87** [comment]
> So should we merge it?

waiting confirmation form @motame

**Comment by volodymyrss** [comment]
please check @motame ! Thanks!

**Pull request merged**
