### PR TITLE
Return progress button

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Comment by burnout87** [comment]
First screenshots:

* when disabled:

image

* when enabled:

image

**Comment by volodymyrss** [comment]
maybe move it higher, and it should be rather "view more" like where INTEGRAL "more" button is.

**Comment by burnout87** [comment]
above the progress bar

image

**Comment by burnout87** [comment]
opening a new tab ... (then I will test also another modal window opening with the output inside)

https://github.com/oda-hub/mmoda-frontend-module/assets/3757833/2fca88c6-43fd-4417-8a6c-3e05b69edd2e

**Comment by burnout87** [comment]
And opened in a modal dialog

https://github.com/oda-hub/mmoda-frontend-module/assets/3757833/ba77d0c7-4632-45e0-b1d5-011ca429c8e0

**Comment by volodymyrss** [comment]
For me, that's pretty nice! If we try it with some more real data, we can get feedback of @andriineronov  and others.

**Comment by burnout87** [comment]
Two first, more concrete, examples

https://github.com/oda-hub/mmoda-frontend-module/assets/3757833/7d30e6cb-aa0f-44f3-acd5-85fa1d29518a


https://github.com/oda-hub/mmoda-frontend-module/assets/3757833/6bfd5b87-6c47-4191-9543-2a87eae212cb

**Comment by burnout87** [comment]
another demo example:


https://github.com/oda-hub/mmoda-frontend-module/assets/3757833/37743d16-e9d1-49d5-9294-1761cf1e43ba

**Comment by burnout87** [comment]
The following three changes are required:

* dispatcher: https://github.com/oda-hub/dispatcher-app/pull/648 (that also addresses https://github.com/oda-hub/dispatcher-app/issues/643) and https://github.com/oda-hub/dispatcher-app/pull/647 (to handle the `progress` job status to be visualized over the frontend)
* dispatcher-plugin-nb2workflow https://github.com/oda-hub/dispatcher-plugin-nb2workflow/pull/81 (to set the status output from the `get_progress_run` to `progress`)
* nb2workflow https://github.com/oda-hub/nb2workflow/pull/135

**Comment by burnout87** [comment]
* add recurrent request, so the notebook updates real-time
* use max_progress returned with the return_progress oda_api function (default 100)
* hide color legend if not needed
* bar should change color depending on the status returned
* think of a different text than "View more"

**Comment by burnout87** [comment]
> 
>     * hide color legend if not needed

Integral legend is now not visible if the instrument is not from INTEGRAL

image

**Comment by burnout87** [comment]
Placing the link to request the progress next to the status as discussed, and different text

image

**Comment by volodymyrss** [comment]
Oh, can you research and recommend a tool for drafting UI? So that we can play around and show how we would imagine it.

Else I can just do it in GIMP or something.

**Comment by burnout87** [comment]
I started the refactoring on the way the progress_report are shown, and I now can display the progress and stage returned from with the `ProgressReported`

[progress_open_modal_progress_details.webm](https://github.com/oda-hub/mmoda-frontend-module/assets/3757833/ed49d264-71e7-40f9-a431-e92c24a3c34e)

**Comment by burnout87** [comment]
> Oh, can you research and recommend a tool for drafting UI? So that we can play around and show how we would imagine it.
> 
> Else I can just do it in GIMP or something.

I know [figma](https://www.figma.com/), quite powerful, perhaps a bit too much for our purposes
After some research I found [zeplin](https://zeplin.io/) to have good reviews

**Comment by burnout87** [comment]
I make the progress-bar color change depending on the returned status, of course the choice is to be improved, currently is the following:

* submitted -> lightgreen
* progress -> lightblue
* failed -> red
* ready -> lightyellow
* done -> green


[demo_video_processing_sleeping_nb2workflow.webm](https://github.com/oda-hub/mmoda-frontend-module/assets/3757833/c3cd4829-a060-4c07-817a-877c696db13d)

**Comment by burnout87** [comment]
[demo_video_processing_sleeping_nb2workflow_refactored_modal.webm](https://github.com/oda-hub/mmoda-frontend-module/assets/3757833/5860fece-3b45-4631-81bc-521951773499)

**Comment by volodymyrss** [comment]
> Now the modal has been refactored using Figma design
> demo_video_processing_sleeping_nb2workflow_refactored_modal.webm

not too bad. There are some things I'd change a bit with distances and so. Also the "get details" link, maybe better to always show it but disabled, unless it's usable.

Also, maybe progress bar :
* on "submitted" yellow and full-width
* on "progress"  is green and has width which is the ratio of reported progress value and progress_max.
* on "ready" is green and full width

**Comment by burnout87** [comment]
implemented some of the suggestions, now both links are visible and become clickable when needed
what do you think about the color choice ?

[demo_video_processing_sleeping_nb2workflow_refactored_modal_2.webm](https://github.com/oda-hub/mmoda-frontend-module/assets/3757833/ab94e90c-578f-47cd-adbb-6708853c1bbd)

and here an isgri image dummy request to see how the refactored modal windows handles the current requests

[demo_video_processing_sleeping_isgri_dummy_modal.webm](https://github.com/oda-hub/mmoda-frontend-module/assets/3757833/97789d43-0c89-42a3-9b2e-b53ee0c5f252)

**Comment by volodymyrss** [comment]
Not bad, just the "preparing request" is a bit too affirmatively green to me. Maybe something grayer or so.

Also, for INTEGRAL, does it show the table when it's processing like before?

**Comment by burnout87** [comment]
> Not bad, just the "processing request" is a bit too affirmatively green to me. Maybe something grayer or so.

Something like that ?

image

**Comment by burnout87** [comment]
> 
> Also, for INTEGRAL, does it show the table when it's processing like before?

and here a test where the table with the status updates from jemx backend are returned

[demo_video_processing_isgri_real_modal.webm](https://github.com/oda-hub/mmoda-frontend-module/assets/3757833/e5db1205-bbe7-4490-affc-c1312446824b)

**Comment by burnout87** [comment]
Moving the legend closer to the table makes it clearer to what it is applied to:

image

image

**Comment by burnout87** [comment]
and another one, looks much better in my opinion

[demo_video_processing_sleeping_nb2workflow_refactored_modal_3.webm](https://github.com/oda-hub/mmoda-frontend-module/assets/3757833/b129717f-357b-4802-b803-10c61dfd9d34)

**Comment by volodymyrss** [comment]
Progress should be filled up from 0 to full.

In demo let's show many steps, 5 steps.

**Comment by volodymyrss** [comment]
Progress should be filled up from 0 to full.

In demo let's show many steps, 5 steps.

**Comment by burnout87** [comment]
all the steps are now shown, from `processing request` to `ready` and then done
when `ready`, I changed the font color to white to make it more visible

[demo_video_processing_sleeping_nb2workflow_refactored_modal_4.webm](https://github.com/oda-hub/mmoda-frontend-module/assets/3757833/77d6e102-11ba-4fa8-a8e4-da4f94357ec0)

**Comment by volodymyrss** [comment]
Also enable notebook output when progress is never returned.

**Comment by burnout87** [comment]
- links on top of each other
  - more details -> no text, make the progress-bar clickable (message icon) 
  - Get current output -> View notebook progress/state (jupyter icon, perhaps just the icon and move it to the right)
- remove arrows
- put some margin

**Comment by burnout87** [comment]
no "more details" link and added jupyter icon

enabled:
image

disabled:
image

**Comment by volodymyrss** [comment]
Thanks! What I had in mind when we talked is just the jupyter icon (no text) maybe to the right of right of the progress bar. Could you give it a try?

**Comment by burnout87** [comment]
> Thanks! What I had in mind when we talked is just the jupyter icon (no text) maybe to the right of right of the progress bar. Could you give it a try?

image

**Comment by volodymyrss** [comment]
> > Thanks! What I had in mind when we talked is just the jupyter icon (no text) maybe to the right of right of the progress bar. Could you give it a try?
> 
> image

Thanks! For me - this is good. Just please record a video?

But I'd really like input of @andriineronov @ferrigno @dsavchenko , maybe they had something else in mind.

**Comment by dsavchenko** [comment]
The text "View notebook progress" may appear on hover over this icon
Do icon become gray if not available?
Isn't it a bit too small? 

But in general, it's good for me

**Comment by burnout87** [comment]
here a first example

[demo_video_processing_sleeping_nb2workflow_refactored_modal_5.webm](https://github.com/oda-hub/mmoda-frontend-module/assets/3757833/75f0bd73-bcaa-4dfb-ac05-c423f2e0ed8f)

**Comment by burnout87** [comment]
> The text "View notebook progress" may appear on hover

good point, I will add a toolip

> Do icon become gray if not available? 

yes it does

> Isn't it a bit too small?

it is because it has the same height as the progress-bar

**Comment by volodymyrss** [comment]
> The text "View notebook progress" may appear on hover over this icon 

Good idea.

> Do icon become gray if not available? 

Indeed it should.

> Isn't it a bit too small?

It also seems small to me, but larger will clash with bar width.

> 
> But in general, it's good for me

**Comment by volodymyrss** [comment]
Looking on video, it's also not ideal that the bar is narrower than other "full-width" elements like he yellow bar.
Maybe we can move the icon below? Above?..

**Comment by burnout87** [comment]
tooltip

image

**Comment by burnout87** [comment]
> Looking on video, it's also not ideal that the bar is narrower than other "full-width" elements like he yellow bar. Maybe we can move the icon below? Above?..

below

image

above

image


If we keep the icon, I'd rather have it next to the bar, but indeed it clashes with the yellow bar below
At this point, perhaps I'd see better to keep the text as before + the icon, below the progress-bar

**Comment by volodymyrss** [comment]
Maybe if also the yellow bar is the same width as the progress bar, shorter than the modal?

**Comment by ferrigno** [comment]
In the video, it does not look clear how to make appear the notebook current status. It appears out of the blue. For the rest, I have not big suggestions.

**Comment by burnout87** [comment]
> Maybe if also the yellow bar is the same width as the progress bar, shorter than the modal?

something like that? I also tried to increase the height of the progress-bar by few pixels, that allowed me to consistently increase the size of the jupyter logo

image

**Comment by volodymyrss** [comment]
> > Maybe if also the yellow bar is the same width as the progress bar, shorter than the modal?
> 
> something like that? I also tried to increase the height of the progress-bar by few pixels, that allowed me to consistently increase the size of the jupyter logo. It can be even bigger, but that wouldn't be that nice
> 
> image

Maybe a bit bigger? With jupyter in it?

image

**Comment by burnout87** [comment]
with the text inside

image

**Comment by burnout87** [comment]
another little video demo, it looks good to me:

[demo_video_processing_sleeping_nb2workflow_refactored_modal_6.webm](https://github.com/oda-hub/mmoda-frontend-module/assets/3757833/4f2ed558-a6c9-41c7-a718-cf10b51d1ae4)

**Comment by burnout87** [comment]
another little video demo, looks good to me. later I will make one also for the visualization of the messages by clicking the progress-bar

[demo_video_processing_sleeping_nb2workflow_refactored_modal_7.webm](https://github.com/oda-hub/mmoda-frontend-module/assets/3757833/ec78a51b-f25b-4fdd-9691-32cea1c511e1)

**Comment by burnout87** [comment]
about the refactoring of "more details":
a tooltip will be for sure needed

image

image

**Comment by volodymyrss** [comment]
I think we could be happy with this, just more technical thing: jupyter notebook fetch should be possible also when it's done. Also done can be just full progress with ready?

**Comment by dsavchenko** [comment]
Yes, as far as "ready" state means either "done" or "failed", we can get rid of the hack I did for the failed notebook download.

**Comment by burnout87** [comment]
> I think we could be happy with this, just more technical thing: jupyter notebook fetch should be possible also when it's done. Also done can be just full progress with ready?

as of now the progress-bar disappears, so you suggest to keep it there, full?

**Comment by burnout87** [comment]
jupyter notebook logo enabled also with done (also fixed the color of the more details message)

image

**Comment by burnout87** [comment]
removed the redundant "done" message at completion

image

I changed also the behavior of the bar and now it's no longer "stripped", so it doesn't give the user the impression processing is still ongoing. what do you think?

**Comment by volodymyrss** [comment]
> removed the redundant "done" message at completion
> 
> image
> 
> I changed also the behavior of the bar and now it's no longer "stripped", so it doesn't give the user the impression processing is still ongoing. what do you think?

Good not striped at the end.

You try to make the bar taller?

**Comment by burnout87** [comment]
> 
> You try to make the bar taller?

image

**Comment by burnout87** [comment]
And thanks to https://github.com/oda-hub/nb2workflow/pull/148 and https://github.com/oda-hub/dispatcher-plugin-nb2workflow/pull/92 , the glueing-output can now be excluded from the returned html 

image

**Pull request merged**
