### PR TITLE
using label and description extra metadata

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Comment by burnout87** [comment]
For image type of product

image

**Comment by burnout87** [comment]
The table headers, as well as header of the modal window, are designed to display only sources (from the initial INTEGRAL based approach), which is no longer the case. Changing it and making it more flexible would require refactoring at many different levels.

A simpler approach would be based on using more generic terms, like "Output".

what do you think?

image

**Comment by volodymyrss** [comment]
Ok, lets change to output.

**Comment by burnout87** [comment]
Example

image

**Review by motame — APPROVED** [review]

**Pull request merged**
