### PR TITLE
calling to re-request the token

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Comment by burnout87** [comment]
tested also when user is not logged in

**Comment by dsavchenko** [comment]
Is it really necessary to re-request the token before every POST? This doubles the number of requests

**Comment by burnout87** [comment]
> Is it really necessary to re-request the token before every POST? This doubles the number of requests. Is the token expected to change during these requests?

a new token will be returned at every `get_token` request, but it can be adjusted so that the first one will be re-used

**Comment by burnout87** [comment]
ok now, the previous behavior is restored: the same token is re-used for re-sending the request and avoid  doubling the number of requests

let me know

**Pull request merged**
