### PR TITLE
gw help update

### PR DESCRIPTION
**Pull request by dsavchenko**
Here is the update for GW help page.

As we decided in #114 to try to update help pages without using Mohamed's development instance.
I made changes in my local instance running in container and used "Node export" option to produce the php file (the underlying filesystem is not writable by default). 
@motame  please verify that it is the right way. There are differences in some id's inside, could it cause any inconsistencies?

### CODE REVIEW

**Comment by dsavchenko** [comment]
I make it draft for now to incorporate #159 but my request for validation of the way I do it is still valid

**Comment by motame** [comment]
The page is OK and saved properly in the module help directory.
I install it and it's there at the right place.
The original images are saved properly under sites/default/files/mmoda/help/gw.
However the image styles like 480x480 are not generated under sites/default/files/styles/large/public/mmoda/help/gw/.
The issue is related to the security feature introduced by Drupal since 7.2.
A token (itok) is added to the url like :
src="/mmoda/sites/default/files/styles/large/public/mmoda/help/gw/frontendtoppanegw.png?itok=sD-mnV85"
In Drupal log : "Image Style Access Denied"

It seems that a specific token is generated depending among others on the seed of the Drupal instance.
To allow images to be generated I had to re-insert them.
After that, I was able to uninstall completely the module and install it again and the images are generated properly.

I should investigate to see how to make those tokens cross-instance compatibles ! 

There is a way to bypass them for images only but I don't know if it's OK :
$conf['image_allow_insecure_derivatives'] = TRUE;
in sites/all/default/settings.php

**Comment by motame** [comment]
@volodymyrss and @dsavchenko would you please add :
` $conf['image_allow_insecure_derivatives'] = TRUE;`
To your sites/all/default/settings.php
as settings.php is not available in github

**Comment by volodymyrss** [comment]
> @volodymyrss and @dsavchenko would you please add : ` $conf['image_allow_insecure_derivatives'] = TRUE;` To your sites/all/default/settings.php as settings.php is not available in github

It is actually on github, I add an issue there:

https://github.com/oda-hub/frontend-chart/issues/23

By the way, a point of issue flow: it's better that  if a further action is needed, we do not close an issue until another issue is created to track the following action. Else there is a chance the action is forgotten!

**Pull request merged**
