### PR TITLE
Include messenger in tab names

### PR DESCRIPTION
**Pull request by dsavchenko**

### CODE REVIEW

**Comment by volodymyrss** [comment]
could you provide a screenshot of how it looks like?

**Comment by motame** [comment]
Pulled the branch and seems fine:
firefox_mV6Islljg5

**Comment by volodymyrss** [comment]
ok. But could it be nicer if the messenger was distinguished somehow from the instrument? Bolder? Smaller font? Different color? (from the theme, of course)

**Comment by motame** [comment]
> ok. But could it be nicer if the messenger was distinguished somehow from the instrument? Bolder? Smaller font? Different color? (from the theme, of course)

If like that, I propose to separate the messenger field from the instrument name.
```
function mmoda_antares_instrument_info() {
  $info = array (
      'name' => 'antares',
      'messenger' => 'Neutrino', 
      'title' => 'Antares',
  );
  return $info;
}
```
instead of 
```
function mmoda_antares_instrument_info() {
  $info = array (
      'name' => 'antares',
      'title' => 'Neutrino<br>Antares',
  );

  return $info;
}

```

and let the system render the tab name with the necessary highlights (CSS classes).

**Comment by motame** [comment]
I made the changes on this branch !
If it's OK, I push my changes and proceed with the merge.

**Comment by motame** [comment]
firefox_VPipUU2lUe

**Comment by dsavchenko** [comment]
I'm the author of this PR, so I can't say “approve” for your changes. But I totally agree with them.

**Review by volodymyrss — APPROVED** [review]

**Comment by motame** [comment]
Indeed, yes !
I'll push soon my changes to the branch then accept the pull request.

**Pull request merged**
