### PR TITLE
Extended list of parameters within the url to ignore and some comments

### PR DESCRIPTION
**Pull request by burnout87**

### CODE REVIEW

**Review by volodymyrss — APPROVED** [review]
I am not completely sure this is the entire list, but it's good.

**Comment by volodymyrss** [comment]
> > I am not completely sure this is the entire list, but it's good.
> 
> Me neither. For that purpose I made a note to remind us to keep such list in synch with the one within the dispatcher:
> 
> https://github.com/oda-hub/dispatcher-app/blob/c907154233355b2aced684f0f677a02eddeb1723/cdci_data_analysis/analysis/hash.py#L5-L13

it is unclear why some of these extra parameters are even inserted in the URL. Some are excluded from URL, right?  Which ones?

**Comment by burnout87** [comment]
> 
> it is unclear why some of these extra parameters are even inserted in the URL. Some are excluded from URL, right? Which ones?

For the URL generation those are:

https://github.com/oda-hub/dispatcher-app/blob/c907154233355b2aced684f0f677a02eddeb1723/cdci_data_analysis/analysis/email_helper.py#L109-L128

**Comment by burnout87** [comment]
> > I am not completely sure this is the entire list, but it's good.
> 
> Me neither. For that purpose I made a note to remind us to keep such list in synch with the one within the dispatcher:
> 
> https://github.com/oda-hub/dispatcher-app/blob/c907154233355b2aced684f0f677a02eddeb1723/cdci_data_analysis/analysis/hash.py#L5-L13

Actually I didn't specify enough, this list is used during the generation and validation of the `job_id` and not for the URL

**Comment by volodymyrss** [comment]
> > > I am not completely sure this is the entire list, but it's good.
> > 
> > 
> > Me neither. For that purpose I made a note to remind us to keep such list in synch with the one within the dispatcher:
> > https://github.com/oda-hub/dispatcher-app/blob/c907154233355b2aced684f0f677a02eddeb1723/cdci_data_analysis/analysis/hash.py#L5-L13
> 
> Actually I didn't specify enough, this list is used during the generation and validation of the `job_id` and not for the URL

yeah, but why there are two lists? It's possible that one list, the extended one, would be sufficient.
Maybe can add a TODO and a reference to other list location somewhere?

Let's not change any more it now, it will break.

**Pull request merged**
